spring.application.name=myzooapp
spring.datasource.url=jdbc:postgresql://localhost:5432/my_java_db

spring.datasource.password=;;;;
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

logging.level.com.luv2code.springbok.demo.SOAPpy=DEBUG

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
